services:
  app:
    build: .
    environment:
      - INFLUXDB_URL=http://influx:8086
      - INFLUXDB_TOKEN=secret-auth-token
      - INFLUXDB_ORG=organization
      - INFLUXDB_BUCKET=bucket
    depends_on:
      influx:
        condition: service_healthy
  influx:
    image: influxdb:2
    ports:
      - 8086:8086
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
      - ./influxdb/config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=username
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=organization
      - DOCKER_INFLUXDB_INIT_BUCKET=bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=secret-auth-token
    healthcheck:
      test: "curl -f http://localhost:8086/ping"
      interval: 5s
      timeout: 10s
      retries: 5
