version: "3"

tasks:
  run:
    cmds:
      - go run src/main.go
    desc: "Run the Go program"
  build:
    cmds:
      - go build src/main.go
    desc: "Build the Go program"
  docker:run:
    cmds:
      - docker compose up --build
    desc: "Build and run the docker compose file"
